[package]
name = "invaders"
version = "0.1.0"
authors = ["imoisejevs <iljamoisejevs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "*"
rusty_audio = "*"
rusty_time = "*"